name: test_env_ocetrac
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - xarray
  - dask
  - scikit-image
  - tqdm
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]